spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    thymeleaf:
        cache: false
  #jdbc
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board_pt?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

#mybatis
mybatis:
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: board



